### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by b4ssey** [googlesamples/android-BluetoothChat#43]
Hello, I'm really a fan of your work, but it isnt compiling on my Android Studio. I really need help as it pertains to my final year project

**Comment by jayesh343oyo** [comment]
`2019-03-04 16:33:42.950 11569-11569/com.example.android.bluetoothchat E/BluetoothAdapter: Bluetooth binder is null
2019-03-04 16:33:43.106 11569-11569/com.example.android.bluetoothchat D/AndroidRuntime: Shutting down VM
2019-03-04 16:33:43.116 11569-11569/com.example.android.bluetoothchat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.bluetoothchat, PID: 11569
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.isEnabled()' on a null object reference
        at com.example.android.bluetoothchat.BluetoothChatFragment.onStart(BluetoothChatFragment.java:110)
        at android.support.v4.app.Fragment.performStart(Fragment.java:2287)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1458)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
        at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3186)
        at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:203)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:582)
        at com.example.android.common.activities.SampleActivityBase.onStart(SampleActivityBase.java:39)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-03-04 16:33:43.140 11569-11569/com.example.android.bluetoothchat I/Process: Sending signal. PID: 11569 SIG: 9
2019-03-04 16:33:43.151 1873-1888/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2019-03-04 16:33:43.151 1873-1888/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
`
